api_platform:
    title: ScoutReady API
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']

    swagger:
        api_keys:
            X-API-KEY:
                name: X-API-KEY
                type: header
